version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: sqlalchemy-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinema
      TEST_POSTGRES_DB: test_cinema  # ✅ Define um banco separado para testes
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinema"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: sqlalchemy-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:admin@db:5432/cinema
      DOCKER_ENV: "true"
