name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: cinema
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d cinema"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m venv venv
          echo "source venv/bin/activate" >> $GITHUB_ENV
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.tx

      - name: Run Migrations
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:admin@localhost:5432/cinema
        run: |
          source venv/bin/activate
          python database.py

      - name: Verify pytest installation
        run: python -m pytest --version

      - name: List project directory
        run: ls -R

      - name: Run Tests
        run: pytest tests/ --disable-warnings --maxfail=1


  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t sqlalchemy-app .
          docker tag sqlalchemy-app ${{ secrets.DOCKER_USERNAME }}/sqlalchemy-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sqlalchemy-app:latest
